FROM node:20-alpine

WORKDIR /app

COPY admin-backoffice/package.json admin-backoffice/package-lock.json ./
RUN npm ci

COPY admin-backoffice .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
