FROM node:20-alpine

WORKDIR /app

COPY parciales/Parcial2/admin-backoffice/package.json parciales/Parcial2/admin-backoffice/package-lock.json ./
RUN npm ci

COPY parciales/Parcial2/admin-backoffice/ ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
