FROM node:20-alpine

WORKDIR /app

COPY parciales/Parcial2/package.json parciales/Parcial2/package-lock.json ./
RUN npm ci

COPY parciales/Parcial2/ ./

EXPOSE 3000

CMD ["npm", "run", "dev:storefront", "--", "--host", "0.0.0.0", "--port", "3000"]
